blank_issues_enable: false
contact_links:
  - name: Feature issue
    url: https://github.com/willfynch/reactspacexapp/issues/new?assignees=robinDevs,willfynch,tapamedina,PierreTerrasson64&labels=good%20first%20issue&template=feature_new.md&title=%5BFeature%5D+-+
    about: This issue template is only used for new features.
  - name: Bug report
    url: https://github.com/willfynch/reactspacexapp/issues/new?assignees=robinDevs,willfynch,tapamedina,PierreTerrasson64&labels=bug&template=report_bug.md&title=%5BBUG%5D+-+
    about: This bug template is only used to report bug issue.
