blank_issues_enable: false
contact_links:
  - name: Feature issue
    url: https://github.com/capywebformation/template-vue/issues/new?assignees=&labels=Type%3A%20Feature&template=feature_new.md&title=%5BFeature%5D+-+
    about: This issue template is only used for new features.
  - name: Bug report
    url: https://github.com/capywebformation/template-vue/issues/new?assignees=&labels=%E2%80%8BType%3A%20Bug%E2%80%8B&template=report_bug.md&title=%5BBUG%5D+-+
    about: This bug template is only used to report bug issue.
